# Generated by Django 4.2.4 on 2023-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='symbol',
        ),
        migrations.AddField(
            model_name='crypto',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='rank',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
